services:
  - type: web
    name: telegram-movie-bot
    env: python
    region: oregon
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.9
